name: Build C# WinForms app

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build
        run: msbuild /t:Build /p:Configuration=Release

      - name: Publish
        run: msbuild /t:Publish /p:Configuration=Release /p:PublishDir="bin\Release"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: "*/bin/Release/"

#      - name: Building the installer
#        run: |
#          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "inno_setup.iss"
#        shell: cmd
#
#      - name: Upload installer artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: Installer
#          path: bin\Release\SeriLinkSetup.exe
          